install command added

diff --git a/bin/sherpa b/bin/sherpa
--- a/bin/sherpa
+++ b/bin/sherpa
@@ -301,26 +301,26 @@ echo "  -q | --quiet      Continue force execution."
 br
 p "${strong}${txtBlue}Commands:${x}"
 p "  ${txtGreen}build${x}, ${txtGreen}b${x}    Compile the curent package"
-p "  ${txtGreen}check${x}, ${txtGreen}c${x}    Analyse the current package"
-p "  ${txtGreen}clean${x}       Remove the target directory"
 p "  ${txtGreen}doc${x}, ${txtGreen}d${x}      Build the package documentation"
 p "  ${txtGreen}edit${x}, ${txtGreen}e${x}     Open files in default Editor"
 p "  ${txtGreen}init${x}        Create package in existing dir"
-p "  ${txtGreen}link${x}        Manakge symlinks on files or dirs"
+p "  ${txtGreen}links${x}        Show symlinks from .sherpa/bin"
 p "  ${txtGreen}new${x}         Create a new sherpa package"
 p "  ${txtGreen}run${x}, ${txtGreen}r${x}      Build and run a binary or script"
 p "  ${txtGreen}test${x}, ${txtGreen}t${x}     Run the tests from the tests dir"
 br
-p "See '${txtGreen}${strong}sherpa${x}${txtGreen} help <command>${x}' for more information on a specific command."
+p "Comming soon: the Docs website, and the link will be here."
 br
 }
 while getopts ":hvc:Vq-:" opt; do
 case $opt in
 h)
 usage
+exit 0
 ;;
 v)
 printf "%s v%s\n" "Sh:erpa" "$(get_yaml_item "version" "${SDD}/Sherpa.yaml")"
+exit 0
 ;;
 c)
 color=${OPTARG}
@@ -335,10 +335,12 @@ quiet="on"
 case "${OPTARG}" in
 help)
 usage
+exit 0
 ;;
 version)
 printf "%s v%s\n" "$SCRIPT_NAME" "$VERSION"
 [[ -n "$REPO" ]] && printf "Repo: %s\n" "$REPO"
+exit 0
 ;;
 verbose)
 verb="on"
@@ -363,36 +365,21 @@ exit 1
 esac
 done
 shift $((OPTIND - 1))
-declare -g em
+declare -g txtGreen
 declare -g x
 if [[ "$#" == 0 ]]; then # Home Route
 clear
-h1 " Welcome to 👋 Sh:erpa"
+h1 " Welcome to the Basecamp 👋"
 hr "= + =" "-" # -----------= + =-----------
 text-center "$(date +%T)"
 br
 br
-h2 "A glimpse of what we can do so far:"
+h2 "What that page might become?"
 br
-p "* Modular structure instead of all-in"
-p "* GetOpt short & long Flags pre-configured"
-p "* Fetch remote Json API data"
-p "* CRUD on local .yaml data files"
-p "* Cargo'like projects management"
-p "* Pug'like semantic text output"
-p "* Custom CSS'like formating"
-p "* CDN'like loading external libs"
-p "* Oh-MyBash'like Custom directory"
-p "* Source libs with ${em}'use \"std/fmt\"'${x}"
-p "* Docs generations via Shdoc & Bashdoc"
-p "* Check syntax with ShellCheck"
-p "* Integrated Tests suite via BashUnit"
-p "* Final script minimization after docs gen'"
-p "* Compile to a binary via SHC"
-p "* Included external programs in .sherpa/bin"
-p "* Next: Somehow dependencies management & publishing"
+p "Eventually some sort of dashboard or old-school portal."
+p "${txtGreen}Sh:erpa${x} version (local & remote), latest news & links"
 br
-p "$(strong "TODO:")"
+p "Time will tel, but anyway ...nice to have you with us ;)"
 br
 fi # End Home Route
 if [[ "$1" == "bashdoc" ]]; then # Bashdoc
@@ -756,3 +743,66 @@ exit 1
 fi
 bashunit tests
 fi
+use "tent/symlink"
+if [[ "$1" == "install" ]]; then # Start Route
+shift
+name=""
+url=""
+type=""
+while getopts "n:t:u:" opt; do
+case $opt in
+n) name=${OPTARG} ;;
+t) type=${OPTARG} ;;
+u) url=${OPTARG} ;;
+*) echo "Invalid flag" ;;
+esac
+done
+[[ ! -d "${SCD}/bbr" ]] && mkdir "${SCD}/bbr"
+[[ ! -d "${SCD}/bbr/exe" ]] && mkdir "${SCD}/bbr/exe"
+[[ ! -d "${SCD}/bbr/lib" ]] && mkdir "${SCD}/bbr/lib"
+if [[ $# == 0 ]]; then
+br
+h1 "Install a BashBox from Git"
+hr "+" "-"
+p "Usage: ${em}sherpa install foobar${x}"
+p "   or: ${em}sherpa install -n='name' -t='bin' -u='url-to-repository'${x}"
+br
+p "If part of the BashBoxRegistry, the name is enough."
+p "If not, a full url to the repository is expected, with following flags:"
+p "-n name: Project's name... n=\"projName\""
+p "-t type: Either bin or lib"
+p "-u  url: Full url to the repository"
+exit 1
+fi
+if [[ -n $url ]]; then # ifUrl
+p "name: $name"
+p "type: $type"
+p "url: $url"
+br
+if [[ -z $type ]]; then # typeCheck
+p "If the -u flag is used, -t must be also set."
+p "The -t flag must be either -t='bin' or -t='lib'"
+exit 1
+elif [[ $type != "bin" && $type != "lib" ]]; then
+p "The -t flag must be either -t='bin' or -t='lib'"
+fi # End typeCheck
+if [[ $type = "bin" ]]; then # installBin
+if [[ -z "$name" ]]; then
+p "The name can't be empty"
+p "use: sherpa install -n='name' -t='bin' -u='repoUrl'"
+exit 1
+fi
+git clone "$url" "${SCD}/bbr/bin/${name}"
+cd "${SCD}/bbr/bin/${name}" || return
+sherpa build
+fi # End installBin
+if [[ $type = "lib" ]]; then # installLib
+git clone "$url" "${SCD}/bbr/lib/${name}"
+p "Creating a symlink into ${SCD}/lib"
+ln -s "${SCD}/bbr/lib/${name}" "${SCD}/lib/${name}"
+fi #End installLib
+fi # End ifUrl
+if [[ -n $2 ]]; then # from BashBoxRegistry
+p "Arg no2: ${2}"
+fi #End from BashBoxRegistry
+fi # End Route
